name: postor
description: A wrapper around Dart's http package, which supports Manageable Requests Cancellation, Request Policy (Timeout and Retry), Easier Multipart Requests, etc.
version: 0.0.4
repository: https://www.github.com/iandis/postor
issue_tracker: https://www.github.com/iandis/postor/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ctmanager: ^0.0.2
  http: ^0.13.3
  meta: ^1.3.0
  path: ^1.8.0
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.1
  fake_async: ^1.2.0
  http_parser: ^4.0.0
  lint: ^1.6.0
  mockito: ^5.0.14
  test: ^1.17.0
