name: postor
description: A wrapper around Dart's http package, which supports Request
  Cancellation, Request Policy (Timeout, Retry), File Upload/Download, etc.
version: 0.0.1+0
repository: https://www.github.com/iandis/postor
issue_tracker: https://www.github.com/iandis/postor/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ctmanager: ^0.0.1+2
  http: ^0.13.3
  meta: ^1.7.0
  retry: ^3.1.0

dev_dependencies:
  lint: ^1.6.0
  test: ^1.17.0
